// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2GZRG1syC7Sh0DFrRfURVUv1MDmqlkcE',
    appId: '1:287490913750:web:269b07090f59708498a077',
    messagingSenderId: '287490913750',
    projectId: 'stats-agent-4a718',
    authDomain: 'stats-agent-4a718.firebaseapp.com',
    storageBucket: 'stats-agent-4a718.firebasestorage.app',
    measurementId: 'G-EH4ZDGXN34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4ZW__KVHO6MVysPE5N2unVd_PY-vuygo',
    appId: '1:287490913750:android:10f7a4a46b4f4e2b98a077',
    messagingSenderId: '287490913750',
    projectId: 'stats-agent-4a718',
    storageBucket: 'stats-agent-4a718.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5s9exJ3dKWF02ewF8lzdrDitqbFqIdWk',
    appId: '1:287490913750:ios:c2c7009f69f8879e98a077',
    messagingSenderId: '287490913750',
    projectId: 'stats-agent-4a718',
    storageBucket: 'stats-agent-4a718.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5s9exJ3dKWF02ewF8lzdrDitqbFqIdWk',
    appId: '1:287490913750:ios:c2c7009f69f8879e98a077',
    messagingSenderId: '287490913750',
    projectId: 'stats-agent-4a718',
    storageBucket: 'stats-agent-4a718.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2GZRG1syC7Sh0DFrRfURVUv1MDmqlkcE',
    appId: '1:287490913750:web:baf809029f18d53398a077',
    messagingSenderId: '287490913750',
    projectId: 'stats-agent-4a718',
    authDomain: 'stats-agent-4a718.firebaseapp.com',
    storageBucket: 'stats-agent-4a718.firebasestorage.app',
    measurementId: 'G-K09N9JQN2L',
  );

}